# Setup
title:               ICT-List
tagline:             'Internet Comparison Table - List'
description:         'Domain registars, cloud storage, CDN, Internet Comparison Table - List'
url:                 https://dw5.github.io/ict-list
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
